### ISSUE TITLE
Unable to sync my Gmail mailbox in MacOS

### ISSUE THREAD

**Issue by jaideeprana** [LukeSmithxyz/mutt-wizard#725]
I still have old stale mails in my inbox.
When I try to run mw -Y, I get the following message:

<img width="214" alt="Screenshot 2021-06-15 at 6 55 49 PM" src="https://user-images.githubusercontent.com/3875065/122060532-502caf80-ce0b-11eb-8f12-039b7591a137.png">

Let me know if I need to provide any additional info.

**Comment by Kr1ss-XD** [comment]
Thank you @jaideeprana ,

should be fixed.

**Comment by jaideeprana** [comment]
After your changes I am not seeing the error related pidof but still my mailbox contains stale mails.

Any idea what could be the issue?

**Comment by Kr1ss-XD** [comment]
Probably, you need to add
```mbsynrc
Remove	Both
```

to your `.mbsyncrc` file. The file should be directly inside your home folder. You can add that clause to the `Channel <gmail-account>` section, where you should already have `Expunge Both`.

**Comment by jaideeprana** [comment]
Tried the above but still no luck only able to get mails till 21/05/23 05:03AM.
